version: v1.0
name: Image builder
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004
blocks:
  - name: semantic-release
    task:
      secrets:
        - name: semantic-release
        - name: docker-hub
        - name: ms-phone
      prologue:
        commands:
          - sudo chmod -R 0777 /etc/docker
          - 'echo ''{"experimental":true}'' > /etc/docker/daemon.json'
          - sudo service docker restart
          - sem-version node 16
          - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@8
          - checkout
          - cache restore node-$(checksum pnpm-lock.yaml)
          - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      jobs:
        - name: pnpm semantic-release
          commands:
            - pnpm semantic-release
